226 add parity to fertility module
Leeds-MRG/Minos pull request #259
Opened 2023-06-05 11:27 UTC by paddy-r

2023-07-27 11:42 UTC, ld-archer requested changes
All testing good and changes look fine. I've added some comments to certain scripts mostly for stuff that I don't think is needed anymore, with one other change to the ordering of modules that needs a little tweak. Should be good to merge when you've addressed the comments, cheers.

2023-07-27 11:42 UTC, ld-archer commented on minos/data_generation/US_missing_LOCF.py
Just need to change the docstring for this, was written with education in mind but being used for nkids_ind now as well.

2023-07-27 11:42 UTC, ld-archer commented on minos/minosPipeline/RunPipeline.py
> +# Replenishment component first, then intervention(s), then fert/mort, then everything else
Think the order should be slightly different here. Should be:
1. Replenishment
2. Fert/Mort
3. Income
4. Intervention
5. Everything else

2023-07-27 11:42 UTC, ld-archer commented on minos/modules/replenishment.py
> +                        'nkids_ind_new',
Are `nkids_ind_raw` or `nkids_ind_new` used in the fertility module or rest of the pipeline? If not (or if any aren't used) they might be better being removed from the dataframe before entering the pipeline.

2023-07-27 11:42 UTC, ld-archer commented on minos/utils.py
> +def dump_parity(pop,
Is this function still needed? Can it be generalised into something that would be useful for later on? If no to both maybe remove.

2023-07-27 11:42 UTC, ld-archer commented on scripts/Makefile
> +fertility_testing: setup
Target still needed? Remove if not.

2023-07-31 12:53 UTC, paddy-r commented on minos/data_generation/US_missing_LOCF.py
Done in [e5fb2d2](https://github.com/Leeds-MRG/Minos/pull/259/commits/e5fb2d2acb8a8dbbe678d4fdb496a78fe8efcceb)

2023-07-31 12:54 UTC, paddy-r commented on scripts/Makefile
> +fertility_testing: setup
Done in [a90b58e](https://github.com/Leeds-MRG/Minos/pull/259/commits/a90b58e06cb51816b7a34545c3919d61da54337a)

2023-07-31 12:55 UTC, paddy-r commented on minos/utils.py
> +def dump_parity(pop,
Done in [35e4b3e](https://github.com/Leeds-MRG/Minos/pull/259/commits/35e4b3ed14843de42405612838c71485801f7dec)

2023-07-31 12:56 UTC, paddy-r commented on minos/minosPipeline/RunPipeline.py
> +# Replenishment component first, then intervention(s), then fert/mort, then everything else
Need to discuss best way to do this, pending merge and resolving conflicts.

2023-07-31 13:08 UTC, RobertClay approved these changes
Working for me. See no glaring issues in outputs or anything on top of Lukes change requests.

2023-07-31 14:38 UTC, paddy-r commented on minos/minosPipeline/RunPipeline.py
> +# Replenishment component first, then intervention(s), then fert/mort, then everything else
Can't do until after merge but some prep in [ad45938](https://github.com/Leeds-MRG/Minos/pull/259/commits/ad45938ff3eb87c2fd389fc5d86309bb73fd9f48)

2023-08-01 09:58 UTC, paddy-r commented on minos/minosPipeline/RunPipeline.py
> +# Replenishment component first, then intervention(s), then fert/mort, then everything else
Fixed in [be59252](https://github.com/Leeds-MRG/Minos/pull/259/commits/be59252fd0b968d39d8b0284826a3f1bb4da8529)

2023-08-01 14:10 UTC, merged